from flask import Flask, jsonify
app = Flask(__name__)

import test

tasks = [
    {
   "idVmoneyNow":"11156",
   "clientes":[
      {
         "codigoCedente":"266",
         "tipAvelc":"L",
         "tipAvede":"D",
         "tipVenlc":"L",
         "tipVende":"D",
         "itens":[
            {
               "lancamento":"1378448",
               "codigoMovimento":"33",
               "sequencia":"1",
               "dataPartida":"05/07/2018",
               "dataSolicitada":"27/04/2021",
               "valor":"10.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"2.00"
                  },
                  {
                     "dataReferencia":"01/11/2019",
                     "taxadeCorrecao":"1.00"
                  },
                  {
                     "dataReferencia":"01/11/2018",
                     "taxadeCorrecao":"3.00"
                  }
               ]
            },
            {
               "lancamento":"1378646",
               "codigoMovimento":"1",
               "sequencia":"1",
               "dataPartida":"25/04/2021",
               "dataSolicitada":"27/04/2021",
               "valor":"7.76",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"2.00"
                  }
               ]
            },
            {
               "lancamento":"1378507",
               "codigoMovimento":"2",
               "sequencia":"1",
               "dataPartida":"27/09/2021",
               "dataSolicitada":"27/04/2021",
               "valor":"10000.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"3.20"
                  }
               ]
            },
            {
               "lancamento":"1378529",
               "codigoMovimento":"16",
               "sequencia":"1",
               "dataPartida":"16/09/2020",
               "dataSolicitada":"27/04/2021",
               "valor":"40200.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"4.80"
                  },
                  {
                     "dataReferencia":"16/12/2020",
                     "taxadeCorrecao":"1.50"
                  }
               ]
            },
            {
               "lancamento":"1378466",
               "codigoMovimento":"16",
               "sequencia":"1",
               "dataPartida":"31/01/2020",
               "dataSolicitada":"27/04/2021",
               "valor":"57000.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"4.80"
                  },
                  {
                     "dataReferencia":"20/05/2020",
                     "taxadeCorrecao":"1.78"
                  }
               ]
            },
            {
               "lancamento":"1378448",
               "codigoMovimento":"2",
               "sequencia":"1",
               "dataPartida":"16/12/2018",
               "dataSolicitada":"27/04/2021",
               "valor":"627.45",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"2.00"
                  },
                  {
                     "dataReferencia":"01/11/2019",
                     "taxadeCorrecao":"1.00"
                  }
               ]
            },
            {
               "lancamento":"1378511",
               "codigoMovimento":"5",
               "sequencia":"2",
               "dataPartida":"13/04/2020",
               "dataSolicitada":"27/04/2021",
               "valor":"5000.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"2.00"
                  }
               ]
            },
            {
               "lancamento":"1378511",
               "codigoMovimento":"5",
               "sequencia":"1",
               "dataPartida":"18/10/2017",
               "dataSolicitada":"27/04/2021",
               "valor":"5000.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"2.00"
                  },
                  {
                     "dataReferencia":"01/11/2019",
                     "taxadeCorrecao":"1.00"
                  },
                  {
                     "dataReferencia":"01/11/2018",
                     "taxadeCorrecao":"3.00"
                  }
               ]
            },
            {
               "lancamento":"1378345",
               "codigoMovimento":"6",
               "sequencia":"1",
               "dataPartida":"10/09/2015",
               "dataSolicitada":"27/04/2021",
               "valor":"485.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"2.00"
                  },
                  {
                     "dataReferencia":"01/11/2019",
                     "taxadeCorrecao":"1.00"
                  },
                  {
                     "dataReferencia":"01/11/2018",
                     "taxadeCorrecao":"3.00"
                  }
               ]
            }
         ]
      },
      {
         "codigoCedente":"260",
         "tipAvelc":"L",
         "tipAvede":"D",
         "tipVenlc":"L",
         "tipVende":"D",
         "itens":[
            {
               "lancamento":"1378400",
               "codigoMovimento":"33",
               "sequencia":"1",
               "dataPartida":"18/07/2017",
               "dataSolicitada":"27/04/2021",
               "valor":"175.00",
               "variacoes":[
                  {
                     "dataReferencia":"27/04/2021",
                     "taxadeCorrecao":"2.00"
                  },
                  {
                     "dataReferencia":"01/11/2019",
                     "taxadeCorrecao":"1.00"
                  },
                  {
                     "dataReferencia":"01/11/2018",
                     "taxadeCorrecao":"3.00"
                  }
               ]
            }
         ]
      }
   ]
}
]


# @app.route("/")
# def home():
#     return jsonify({'tasks': tasks})

@app.route("/")
def hello():
    return jsonify({'tasks': tasks})
#     return "Olá, moneynow ! "
